rootProject.name = "vital"

include("vital-core")
include("vital-players")
include("vital-commands")
include("vital-inventories")
include("vital-tasks")
include("vital-items")
include("vital-configs")
include("vital-holograms")
include("vital-scoreboards")
include("vital-minigames")
include("vital-full-sample")
include("vital-standalone-sample")
include("vital-databases")
include("vital-core-processor")
include("vital-commands-processor")
include("vital-utils")
